---
-  import_playbook: scripts/qemu.yaml
-  import_playbook: scripts/unattended-upgrades.yaml
-  import_playbook: scripts/docker.yaml
-  import_playbook: scripts/tailscale.yaml
-  import_playbook: scripts/reboot.yaml