---
- name: Update and upgrade all packages on worker nodes
  hosts: all
  tasks:
    - name: Update
      apt:
        update_cache: yes

    - name: Full Upgrade
      apt:
        upgrade: full
        autoremove: yes
        autoclean: yes
