---
- name: Restart all AWS instances
  hosts: aws_ec2
  gather_facts: false
  become: yes
  tasks:
    - name: Rebooting AWS instances
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        reboot_timeout: 60
        pre_reboot_delay: 10
        post_reboot_delay: 10
        test_command: whoami