---
- name: Restart all AWS instances
  hosts: AWS
  gather_facts: false
  become: yes
  tasks:
    - name: Rebooting AWS instances
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        reboot_timeout: 35
        pre_reboot_delay: 5
        post_reboot_delay: 5
        test_command: whoami