---
- name: Install QEMU Agent on Workers
  hosts: workers
  become: true
  tasks:
    - name: Install QEMU Guest Agent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
        update_cache: yes

    - name: Enable and start QEMU Guest Agent service
      ansible.builtin.systemd:
        name: qemu-guest-agent
        enabled: true
        state: started
