---
- name: Add helper scripts to home directory
  hosts: workers
  become: false

  tasks:
    - name: ====== Sync only shell scripts ======
      ansible.builtin.synchronize:
        src: /home/jacksparrow/ansible/files/
        dest: ~/
        delete: true
        rsync_opts:
          - "--include=*.sh"
          - "--exclude=*"